<?php
	
	define('PARAM_TYPE_TEXT',10);
	define('PARAM_TYPE_SELECT',20);
	define('PARAM_TYPE_DATE',30);
	define('PARAM_TYPE_DB_NAME',40);
	define('PARAM_TYPE_DB_TABLE_PREFIX',50);
	define('PARAM_TYPE_DB_TABLE_EMAIL',60);
	define('PARAM_TYPE_PASSWORD',70);
	define('PARAM_TYPE_FILE_PATH',80);
	define('PARAM_TYPE_EMAIL',90);
	define('PARAM_TYPE_ARRAY',80);
	
	define('ACTION_GET_STEP_CONTENT','1');
	define('ACTION_VALIDATE_PARAMS','2');
	
	define('DB_DEFAULT_CHARSET','utf8');
	
	define('REPONSE_CODE_SUCCESS', 1000);
	
	define('ERROR_EMPTY',5100);
	define('ERROR_EXISTS',5200);
	define('ERROR_EMAIL_INVALID',5300);
	define('ERROR_FOLDER_NAME_INVALID',5400);
	
	define('ERROR_UNKNOWN',2000);
	define('ERROR_DB_CONNECTION',2100);
	define('ERROR_FILE_NOT_WRITABLE',2200);
	define('ERROR_PACKAGE_NOT_FOUND',2300);
	define('ERROR_INST_FOLDER_NOT_DEFINED',2400);
	define('ERROR_INSUFFICIENT_PARAMS',2500);
	define('ERROR_DB_INSUFFICIENT_PARAMS_CONNECTION',2600);
	define('ERROR_CONF_MISSING',2700);
	define('ERROR_INST_FOLDER_NOT_FOUND',2800);
 
	define('ERROR_MANIFEST_NOT_FOUND',2900);
	define('ERROR_MISSING_PARAM_VALUE',3000);
	define('ERROR_PARAM_NOT_VALID',3100);
	define('ERROR_PARAM_CONFLICT',3200);
	
	
?>